<a href="https://colab.research.google.com/github/akshayashok-lx/Numpy/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np    # numerical python

#Array -> same collection of data with same datatype (homogeneous)

a=np.array([1,2,3,4,5,6])
print(a)

b=np.array([1,2,3,4,5.6])
print(b)

c=np.array([1,2,3,4,5,"6"])
print(c)



[1 2 3 4 5 6]
[1.  2.  3.  4.  5.6]
['1' '2' '3' '4' '5' '6']


In [2]:
#Slicing = *Forward Slicing and *Backward Slicing

b=np.array([1,2,3,4,5])

print(b[0:2])
print(b[-1:-3:-1])
print(b[3: :])
print(b[-4: :-1])

[1 2]
[5 4]
[4 5]
[2 1]


In [3]:
#Dimension

a=np.array([0])    # ndim is used to check dimension
print(a.ndim)  #n.dim=1 its a vector


b=np.array([[1,2],[3,4]])
print(b.ndim)  #n.dim=2 its a 2d array
print(b)

print(b.shape)   # to check the shape  or know how many  rows and columns eg (2,2) rows =2 ,columns =2

1
2
[[1 2]
 [3 4]]
(2, 2)


In [4]:
# create a 2x2 matrix 2,3,4,5

a=np.array([[2,3],[4,5]])
print(a.ndim)
print(a.shape)
print(a)

2
(2, 2)
[[2 3]
 [4 5]]


In [5]:
# create a 2x3 matrix and print it size , shape and dimensions

a=np.array([[1,2,3],[4,5,6]])
print(a.ndim)
print(a.shape)
print(a)
print(a.size)   # to check how many elements

2
(2, 3)
[[1 2 3]
 [4 5 6]]
6


In [6]:
#create 4x2 matrix and find its size,shape.....

a=np.array([[1,2],[3,4],[5,6],[7,8]])
print(a)
print(a.ndim)
print(a.size)
print(a.shape)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
2
8
(4, 2)


In [7]:
#create a 4x4 matrix and find its ......

a=np.array([[1,2,3,4],[2,3,4,5],[3,4,5,6],[4,5,6,7]])
print(a.size)
print(a.ndim)
print(a.shape)
print(a)

16
2
(4, 4)
[[1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]]


**DAY 2**

In [8]:
import numpy as np

print(a[0])    # to access the specific row
print(a[:,0])  # to acces the specific column
print(a[1,1])  # to acces a apecific number using row and column
print(a[3,2:]) # to acces a set of adjacetnt
print(a[3,0:2])
print(a[2:,2:]) # to print a matrix


[1 2 3 4]
[1 2 3 4]
3
[6 7]
[4 5]
[[5 6]
 [6 7]]


In [9]:
#zero matrix

z=np.zeros([3,3])  #np.zeros is used to prtint a zero matrix , the dimension is given in t he bracket
print(z)

q=np.zeros([3,5],dtype=int) # dtype is used to change th edata type
print(q)

q=np.zeros([3,5],dtype=complex)
print(q)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
[[0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]]


In [10]:
#one matrix

x=np.ones([3,3],dtype=int)
print(x)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [11]:
# create a 2x2 matrix

a=np.array([[1,2],[3,4]])
b=np.array([[3,1],[6,7]])


In [12]:
#matrix addition
print(a+b)
print()

#matrix subtraction
print(a-b)
print()

#matrix multiplication
print(a*b)   #not a matrix maultiplication
print()

print(a@b)
print()

print(a.dot(b))
print()

#matrix division
print(a/b)


[[ 4  3]
 [ 9 11]]

[[-2  1]
 [-3 -3]]

[[ 3  2]
 [18 28]]

[[15 15]
 [33 31]]

[[15 15]
 [33 31]]

[[0.33333333 2.        ]
 [0.5        0.57142857]]


In [13]:
#full matrix
          # if all the elements in the matrix is same it is called full matrix

z=np.full([3,3],5,dtype=int)    #([dimension],elements)
print(z)

[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [14]:
#create a matrix with value 9 and add data type complex

a=np.full([3,3],9,dtype=complex)
print(a)

[[9.+0.j 9.+0.j 9.+0.j]
 [9.+0.j 9.+0.j 9.+0.j]
 [9.+0.j 9.+0.j 9.+0.j]]


In [15]:
# identity matrix

z=np.identity(3)
print(z)
print()

z=np.eye(3)   #it is used to print identity matrix
print(z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [16]:
#create a 4x4 matrix

a=np.array([[1,2,3,4],[2,3,4,5],[3,4,5,6],[4,5,6,7]])
print(a)
print()          #to print blank space

print(a.size)
print()

b=a.reshape(8,2)   # to change the shape of the matrix
print(b)


[[1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]]

16

[[1 2]
 [3 4]
 [2 3]
 [4 5]
 [3 4]
 [5 6]
 [4 5]
 [6 7]]


In [17]:
# arrange a particular range of numbers

a=np.arange(1,10,2)   # start,end+1,step
print(a)

b=np.arange(1,12)
print(b)


[1 3 5 7 9]
[ 1  2  3  4  5  6  7  8  9 10 11]


In [18]:
#create a 5x2 matrix using arange

a=np.arange(1,11).reshape(5,2)
print(a)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [19]:
#create a 3x3 matrix with float  values

a=np.array([[1.2,2.2,2.3],[2.2,3.2,4.2],[6.5,4.5,6.6]])
print(a)

[[1.2 2.2 2.3]
 [2.2 3.2 4.2]
 [6.5 4.5 6.6]]


In [20]:
#floor

z=np.floor(a)   #floor is used to round to lower value
print(z)

[[1. 2. 2.]
 [2. 3. 4.]
 [6. 4. 6.]]


In [21]:
#ceil

z=np.ceil(a)   #ciel is used to round to upper value
print(z)

[[2. 3. 3.]
 [3. 4. 5.]
 [7. 5. 7.]]


In [22]:
#round

z=np.round(a)   #round is used to round to value
print(z)

#incase of .5 it round towards even number eg 3.5 -> 4

[[1. 2. 2.]
 [2. 3. 4.]
 [6. 4. 7.]]


In [23]:
#create a 3x3 matrix

a=np.arange(1,10).reshape(3,3)
print(a)

print(a.max()) # to find the max elememnts in the matrix

print(a.max(axis=1))  # axis is used to find the max element in every row
                      # axis=1 means row
                      # axis=0 means column  in numpy


print(a.min())
print(a.min(axis=1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
9
[3 6 9]
1
[1 4 7]


**DAY 3**


In [33]:
print(a.sum())
print(a.sum(axis=1))
print(a.sum(axis=0))

print()

print(np.sqrt(a))

print()

print(np.sin(a))

print()

print(np.cos(a))

print()

print(np.tan(a))]

print()

print(a.flatten())    # to create a matix into a flat format


45
[ 6 15 24]
[12 15 18]

[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]]

[[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]
 [ 0.6569866   0.98935825  0.41211849]]

[[ 0.54030231 -0.41614684 -0.9899925 ]
 [-0.65364362  0.28366219  0.96017029]
 [ 0.75390225 -0.14550003 -0.91113026]]

[[ 1.55740772 -2.18503986 -0.14254654]
 [ 1.15782128 -3.38051501 -0.29100619]
 [ 0.87144798 -6.79971146 -0.45231566]]

[1 2 3 4 5 6 7 8 9]


In [44]:
# creatae a 3x3 matrix

a=np.arange(3,30,3).reshape(3,3)
print(a)

print(np.sort(a,axis=0))
print()
print(np.sort(a,axis=1))
print()

c=(np.argsort(a,axis=1))     # shows the index of thematrix  (arg)
print(c)

[[ 3  6  9]
 [12 15 18]
 [21 24 27]]
[[ 3  6  9]
 [12 15 18]
 [21 24 27]]

[[ 3  6  9]
 [12 15 18]
 [21 24 27]]

[[0 1 2]
 [0 1 2]
 [0 1 2]]
